### ISSUE TITLE
イベントカレンダの表示

### ISSUE THREAD

**Issue by yoshinari-nomura** [p-salon/modern_times#4]
+ Event モデルに格納されたイベント情報をカレンダ形式で表示する
+ Issue #3 担当者と協調して Event モデルについて調整する

**Comment by kjtbw** [comment]
# 目的
+ fullcalendar を用いて，カレンダを表示する
https://fullcalendar.io/

# そのために必要なこと
+ Reactの導入
  + ライブラリはReactでなくてもいいが，山本が慣れているため，Reactを選択
  + 他の候補としては，Vue, jQueryなどがある．

+ Webpackerの導入
  + ReactをRailsで使うには，Webpackerが必要


# TODO
+ よって，以下の3つのことをやる必要がある
1: Webpackerの導入
2: Reactの導入
3: fullcalendar の利用

# 参考
+ Webpacker とReactの導入
https://qiita.com/kouheiszk/items/c85e70e331ba75841818#152-react%E3%81%AE%E5%B0%8E%E5%85%A5 
+ Reactを用いたfullcalendr の利用
https://fullcalendar.io/docs/react

**Comment by yoshinari-nomura** [comment]
Webpack と React の環境は，一旦マージします

**Comment by yoshinari-nomura** [comment]
一旦閉じて別 issue にします．
